### PR TITLE
Use tag:Name to search for security groups

### PR DESCRIPTION
**Pull request by delkopiso**
For the vpc and subnets we use `tag:Name` to specify which resources we're interested in. There's no reason that I see for why we need to veer away from that and use `group-name` for security groups.

### CODE REVIEW

**Comment by delkopiso** [comment]
Configuration sounds like a good idea, but I think the current behavior is misleading. 

The worry about this breaking change is why we employ semantic versioning. This can published under a new major version, and allow anyone to adopt it when ready.

**Comment by lucasklaassen** [comment]
@jconstance-amplify It looks like we aren't utilizing the github release feature that can keep track of these versions and document them here: https://github.com/amplify-education/serverless-vpc-discovery/releases

**Comment by jconstance-amplify** [comment]
@delkopiso Do you want to add support for configuration and then we can release this under a new major version?

@lucasklaassen Right now we automatically release on merge to master, so we haven't really bothered with Github releases. Maybe something we can think about though.

**Comment by bradennapier** [comment]
Why not look at tag:Name then group name if it fails?  Definitely need this - i dynamicaly create these things so right now i have to manually look up the groupName that is created which changes whenever i do a full provision of my CF Stack - but i generate naming conventions that match across vpc, subnets, and sg

**Pull request closed without merging**
